---

- name: Set distro-specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - default.yml

- name: Install rustup system requirements
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ rustup_packages }}"