version: '3'
services:
  zfx-subzero-node-0:
    image: zfx-subzero-node:latest
    ports:
      - "1234:1234"
    expose:
      - "1234"
    environment:
      - NODE_ID=12My22AzQQosboCy6TCDFkTQwHTSuHhFN1VDcdDRPUe3H8j3DvY
      - NODE_ADDR=host.docker.internal:1234
      - BOOTSTRAP_ID=19Y53ymnBw4LWUpiAMUzPYmYqZmukRhNHm3VyAhzMqckRcuvkf
      - BOOTSTRAP_ADDR=host.docker.internal:1235
      - KEYPAIR=ad7f2ee3958a7f3fa2c84931770f5773ef7694fdd0bb217d90f29a94199c9d7307ca3851515c89344639fe6a4077923068d1d7fc6106701213c61d34ef8e9416
      - KEY_PATH=deployment/test-certs/node0.key
      - CERTIFICATE_PATH=deployment/test-certs/node0.crt
    container_name: zfx-subzero-node-0
    restart: always

  zfx-subzero-node-1:
    image: zfx-subzero-node:latest
    ports:
      - "1235:1235"
    expose:
      - "1235"
    environment:
      - NODE_ID=19Y53ymnBw4LWUpiAMUzPYmYqZmukRhNHm3VyAhzMqckRcuvkf
      - NODE_ADDR=host.docker.internal:1235
      - BOOTSTRAP_ID=12My22AzQQosboCy6TCDFkTQwHTSuHhFN1VDcdDRPUe3H8j3DvY
      - BOOTSTRAP_ADDR=host.docker.internal:1234
      - KEYPAIR=5a353c630d3faf8e2d333a0983c1c71d5e9b6aed8f4959578fbeb3d3f3172886393b576de0ac1fe86a4dd416cf032543ac1bd066eb82585f779f6ce21237c0cd
      - KEY_PATH=deployment/test-certs/node1.key
      - CERTIFICATE_PATH=deployment/test-certs/node1.crt
    container_name: zfx-subzero-node-1
    restart: always

  zfx-subzero-node-2:
    image: zfx-subzero-node:latest
    ports:
      - "1236:1236"
    expose:
      - "1236"
    environment:
      - NODE_ID=1A2iUK1VQWMfvtmrBpXXkVJjM5eMWmTfMEcBx4TatSJeuoSH7n
      - NODE_ADDR=host.docker.internal:1236
      - BOOTSTRAP_ID=19Y53ymnBw4LWUpiAMUzPYmYqZmukRhNHm3VyAhzMqckRcuvkf
      - BOOTSTRAP_ADDR=host.docker.internal:1235
      - KEYPAIR=6f4b736b9a6894858a81696d9c96cbdacf3d49099d212213f5abce33da18716f067f8a2b9aeb602cd4163291ebbf39e0e024634f3be19bde4c490465d9095a6b
      - KEY_PATH=deployment/test-certs/node2.key
      - CERTIFICATE_PATH=deployment/test-certs/node2.crt
    container_name: zfx-subzero-node-2
    restart: always